version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: removebg-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Optional: Mount logs directory if you want to persist logs
      - ./logs:/app/logs
    # Optional: Add resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    # Optional: Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('https://api.telegram.org')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
